services:
  postgres-server:
    container_name: postgres17
    hostname: postgres
    image: postgres:17.1
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DB=bandodedados"
    ports:
      - 5433:5432
